### ISSUE TITLE
New deploy system

### ISSUE THREAD

**Issue by dwradcliffe** [rubygems/rubygems-infrastructure#18]
- [x] deploy shipit
- [x] setup stacks
  - [x] rubygems.org production
  - [x] rubygems.org staging
  - [x] rubygems-status
  - [x] rubygems-lita
  - [x] shipit
- [x] slack notifications
- [x] setup maintenance tasks
- [ ] trigger deploys from slack
- [ ] update playbooks

**Comment by maclover7** [comment]
@dwradcliffe Does Shipit have Heroku support?

**Comment by dwradcliffe** [comment]
@maclover7 Yes it does!

**Comment by maclover7** [comment]
Nice.

**Comment by indirect** [comment]
How's this checklist coming? Seems like it might even be done...

**Comment by dwradcliffe** [comment]
List above hasn't really changed. I need to update the shipit engine (hopefully tomorrow) and then I can get the last things done.
