### ISSUE TITLE
Add SSL certificate(s) for *.cf.rubygems.org

### ISSUE THREAD

**Issue by reedloden** [rubygems/rubygems-infrastructure#25]
Forgive me if there's some other repository I should be filing this issue against.

production.cf.rubygems.org uses CloudFront (d2chzxaqi4y7f8.cloudfront.net), but it doesn't support https://. Same goes for other *.cf.rubygems.org things like staging.cf.rubygems.org.

I am happy to purchase (or donate the money for) an SSL certificate for *.cf.rubygems.org (or individual ones for each CF instance, if it makes better sense). AWS CloudFront supports SSL for free if you use SNI, so there's really no reason why not to enable it.

**Comment by dwradcliffe** [comment]
We're phasing out CloudFront. Last week we updated our Fastly config to go directly to S3 and we should be able to remove any other references as well.

Were you seeing these URLs in use somewhere?

**Comment by reedloden** [comment]
Yes, both https://rubygems.org/pages/download and https://github.com/sstephenson/ruby-build/ use them.

**Comment by reedloden** [comment]
I just opened https://github.com/rubygems/rubygems.org/pull/1026 to fix https://rubygems.org/pages/download

**Comment by dwradcliffe** [comment]
Awesome, thanks!

**Comment by dwradcliffe** [comment]
@reedloden I think we can close this, since all references to CloudFront have been removed.
