### ISSUE TITLE
remove bastion servers

### ISSUE THREAD

**Issue by dwradcliffe** [rubygems/rubygems-infrastructure#41]
@skottler We never ended up requiring the use of the bastion servers, so I think I'm going to remove them. They don't get used and don't really buy us that much. Thoughts?

**Comment by skottler** [comment]
Totally fine with them getting removed. What do you think about two-factor'ing SSH?

**Comment by dwradcliffe** [comment]
I'm not sure how that would work with deploys. Also a bit worried about getting locked out if Duo breaks.
