### ISSUE TITLE
Remove bundler-api (heroku app)

### ISSUE THREAD

**Issue by dwradcliffe** [rubygems/rubygems-infrastructure#42]
We want to retire the bundler-api heroku app and pull both the dependency api and the new index back into the main rubygems.org rails application.

This will help us to not duplicate code, work, and infrastructure. This will greatly simplify the Fastly config and allow us to focus our efforts on one application.

There are two areas that need work for this to happen:
### Dependency API
- https://github.com/rubygems/rubygems.org/pull/966
- https://github.com/rubygems/rubygems.org/pull/1163
### New Index
- https://github.com/rubygems/rubygems.org/pull/1067

@segiddins @maclover7 @indirect @fotanus

cc: @evanphx @qrush @arthurnn

**Comment by segiddins** [comment]
Iirc we also need to ensure that rubygems.org has the infrastructure to collect the usage stats that the bundler API currently collects

**Comment by qrush** [comment]
Are #966 and #1163 ready for review? I can do a read-through if so, but want to hold off if it's WIP.

**Comment by dwradcliffe** [comment]
@qrush Not ready yet. Those two need to be merged into one, rebased, and finished. Very WIP.

**Comment by qrush** [comment]
Sounds good. Happy to read through once they're a little more fully baked. :bread:

**Comment by arthurnn** [comment]
I will work on getting the dependency API, backported. We have a PR already, i will review/merge and finish any remaining work.

**Comment by dwradcliffe** [comment]
Newest PR for dependency API is https://github.com/rubygems/rubygems.org/pull/1225
